    #codecov.io - токен, после добавления репозитория
    env:
      global:
        - CODECOV_TOKEN="a112069b-2f50-4fb9-80fc-9f18477b31b5"

    # используем язык java. Travis CI поддерживает другие языки тоже.
    language: java
    jdk:
      - openjdk16

    # используем режим обычного пользователя для сборки проекта.
    sudo: false

    # после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
    # Здесь используется сторонний сервис https://codecov.io/
    after_success:
      - bash <(curl -s https://codecov.io/bash)

    # Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
    notifications:
      email:
        recipients:
          - i1r@tuta.io
        on_success: never # default: change
        on_failure: always # default: always